//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.19 at 01:26:07 PM CEST 
//

package com.zaglavljeFakture;


import java.math.BigDecimal;
import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.Adapter1;

import lombok.Data;

@Entity
@Data
@XmlAccessorType(XmlAccessType.FIELD)
public class ZaglavljeFakture {

	@XmlTransient
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ZAGLAVLJE_FAKTURE_ID")
	private Long id;
	
	@XmlElement(required = true)
    protected String nazivDobavljaca;
	
    @XmlElement(required = true)
    protected String adresaDobavljaca;
    
    @XmlElement(name = "PIBDobavljaca", required = true)
    protected String pibDobavljaca;
    
    @XmlElement(required = true)
    protected String nazivKupca;
    
    @XmlElement(required = true)
    protected String adresaKupca;
    
    @XmlElement(name = "PIBKupca", required = true)
    protected String pibKupca;
    
    @XmlElement(required = true)
    protected String brojRacuna;
    
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlElement(required = true)
    protected Date datumRacuna;
    
   
    @XmlElement(required = true)
    protected BigDecimal vrednostRobe;
    
    @XmlElement(required = true)
    protected BigDecimal vrednostUsluga;
    
    @XmlElement(required = true)
    protected BigDecimal ukupnoRobaIUsluge;
    
    @XmlElement(required = true)
    protected BigDecimal ukupanRabat;
    
    @XmlElement(required = true)
    protected BigDecimal ukupanPorez;
    
    @XmlElement(required = true)
    protected String oznakaValute;
    
    @XmlElement(required = true)
    protected BigDecimal iznosZaUplatu;
    
    @XmlElement(required = true)
    protected String uplataNaRacun;
    
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(Adapter1.class)
    protected Date datumValute;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNazivDobavljaca() {
		return nazivDobavljaca;
	}

	public void setNazivDobavljaca(String nazivDobavljaca) {
		this.nazivDobavljaca = nazivDobavljaca;
	}

	public String getAdresaDobavljaca() {
		return adresaDobavljaca;
	}

	public void setAdresaDobavljaca(String adresaDobavljaca) {
		this.adresaDobavljaca = adresaDobavljaca;
	}

	public String getPibDobavljaca() {
		return pibDobavljaca;
	}

	public void setPibDobavljaca(String pibDobavljaca) {
		this.pibDobavljaca = pibDobavljaca;
	}

	public String getNazivKupca() {
		return nazivKupca;
	}

	public void setNazivKupca(String nazivKupca) {
		this.nazivKupca = nazivKupca;
	}

	public String getAdresaKupca() {
		return adresaKupca;
	}

	public void setAdresaKupca(String adresaKupca) {
		this.adresaKupca = adresaKupca;
	}

	public String getPibKupca() {
		return pibKupca;
	}

	public void setPibKupca(String pibKupca) {
		this.pibKupca = pibKupca;
	}

	public String getBrojRacuna() {
		return brojRacuna;
	}

	public void setBrojRacuna(String brojRacuna) {
		this.brojRacuna = brojRacuna;
	}

	public Date getDatumRacuna() {
		return datumRacuna;
	}

	public void setDatumRacuna(Date datumRacuna) {
		this.datumRacuna = datumRacuna;
	}

	public BigDecimal getVrednostRobe() {
		return vrednostRobe;
	}

	public void setVrednostRobe(BigDecimal vrednostRobe) {
		this.vrednostRobe = vrednostRobe;
	}

	public BigDecimal getVrednostUsluga() {
		return vrednostUsluga;
	}

	public void setVrednostUsluga(BigDecimal vrednostUsluga) {
		this.vrednostUsluga = vrednostUsluga;
	}

	public BigDecimal getUkupnoRobaIUsluge() {
		return ukupnoRobaIUsluge;
	}

	public void setUkupnoRobaIUsluge(BigDecimal ukupnoRobaIUsluge) {
		this.ukupnoRobaIUsluge = ukupnoRobaIUsluge;
	}

	public BigDecimal getUkupanRabat() {
		return ukupanRabat;
	}

	public void setUkupanRabat(BigDecimal ukupanRabat) {
		this.ukupanRabat = ukupanRabat;
	}

	public BigDecimal getUkupanPorez() {
		return ukupanPorez;
	}

	public void setUkupanPorez(BigDecimal ukupanPorez) {
		this.ukupanPorez = ukupanPorez;
	}

	public String getOznakaValute() {
		return oznakaValute;
	}

	public void setOznakaValute(String oznakaValute) {
		this.oznakaValute = oznakaValute;
	}

	public BigDecimal getIznosZaUplatu() {
		return iznosZaUplatu;
	}

	public void setIznosZaUplatu(BigDecimal iznosZaUplatu) {
		this.iznosZaUplatu = iznosZaUplatu;
	}

	public String getUplataNaRacun() {
		return uplataNaRacun;
	}

	public void setUplataNaRacun(String uplataNaRacun) {
		this.uplataNaRacun = uplataNaRacun;
	}

	public Date getDatumValute() {
		return datumValute;
	}

	public void setDatumValute(Date datumValute) {
		this.datumValute = datumValute;
	}

  
}
